/* BITHOUSE CORE LITE v3 — nome do sócio vem do profile */
(function(){'use strict';
const URL=window.BITHOUSE_SUPABASE_URL,KEY=window.BITHOUSE_SUPABASE_KEY;
if(!window.supabase||!URL||!KEY){console.error('Bithouse: configuração Supabase ausente');return;}
window.sb=window.supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const q=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const fmt=v=>{if(!v)return '—';const d=new Date(String(v).includes('T')?v:v+'T12:00:00');return new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'2-digit'}).format(d)};
window.BH={q,esc,norm,fmt,session:null,user:null,profile:null};let resolveReady;window.BH.ready=new Promise(r=>resolveReady=r);
function setAuth(on){document.documentElement.dataset.auth=on?'yes':'no';q('#app')?.classList.toggle('hidden',!on);q('#login')?.classList.toggle('hidden',on);}
function loginUI(){const box=q('#login');if(!box)return;box.className='login-wrap';box.innerHTML='<div class="login-card"><div class="brand"><span class="brand-mark">✦</span><span>Bithouse</span></div><span class="eyebrow">CENTRAL DE OPERAÇÕES</span><h1>Agenda compartilhada.</h1><p>Entre com seu e-mail da Bithouse para acessar.</p><input id="coreEmail" type="email" autocomplete="email" placeholder="seu@email.com"><button class="primary-btn" id="coreLogin">Enviar link de acesso</button><div id="coreMsg" class="login-message" aria-live="polite"></div></div>';q('#coreLogin').onclick=async()=>{const email=q('#coreEmail').value.trim(),msg=q('#coreMsg');if(!email){msg.textContent='Digite seu e-mail.';return}const {error}=await window.sb.auth.signInWithOtp({email,options:{emailRedirectTo:location.href}});msg.textContent=error?'Não foi possível enviar o link: '+error.message:'Foi enviado o link no seu e-mail. Verifique sua caixa de entrada.';};}
async function hydrate(session){window.BH.session=session||null;window.user=session?.user||null;window.BH.user=window.user;if(window.user){const r=await window.sb.from('profiles').select('id,name,specialty,role').eq('id',window.user.id).maybeSingle();window.BH.profile=r.data||null;window.profile=r.data||null;const n=q('#userName');if(n)n.textContent=r.data?.name||'Selenne';}else{window.BH.profile=null;window.profile=null;}const state=q('#syncState');if(state)state.textContent=window.user?'● conectado':'● aguardando login';setAuth(!!session);resolveReady(window.user);}
async function init(){try{const {data,error}=await window.sb.auth.getSession();if(error)throw error;if(!data.session)loginUI();await hydrate(data.session);window.sb.auth.onAuthStateChange(async(_e,s)=>{await hydrate(s);});}catch(e){console.error('Bithouse sessão:',e);setAuth(false);loginUI();resolveReady(null);}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();