/* BITHOUSE — PHASE 3: production intelligence */
(function(){
'use strict';
const sb=()=>window.sb;
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const canonical=v=>{const s=norm(v);return s==='concluido'?'Concluído':s==='em andamento'?'Em andamento':s==='bloqueado'?'Bloqueado':'Não iniciado'};
let lock=false;
async function syncAgenda(stepId,status){const r=await sb().from('agenda_items').update({status:canonical(status)}).eq('asset_step_id',stepId);if(r.error)console.warn('Agenda sync:',r.error.message)}
async function rollupCommission(id){if(!id)return;const r=await sb().from('agenda_items').select('status').eq('commission_id',id);if(r.error||!r.data?.length)return;const total=r.data.length,done=r.data.filter(x=>norm(x.status)==='concluido').length;await sb().from('commissions').update({progress:Math.round(done/total*100)/100,status:done===total?'Concluído':done?'Em andamento':'Planejamento',updated_at:new Date().toISOString()}).eq('id',id)}
async function changeStep(id,newStatus){if(lock)return;lock=true;try{const r=await sb().from('asset_steps').select('id,asset_id,status,depends_on_step_id,started_at').eq('id',id).maybeSingle();if(r.error||!r.data)throw new Error(r.error?.message||'Etapa não encontrada.');const step=r.data,st=canonical(newStatus);if(st==='Em andamento'&&step.depends_on_step_id){const d=await sb().from('asset_steps').select('status').eq('id',step.depends_on_step_id).maybeSingle();if(d.data&&norm(d.data.status)!=='concluido')throw new Error('Esta etapa ainda está bloqueada pela etapa anterior.')}const patch={status:st,updated_at:new Date().toISOString()};if(st==='Em andamento'&&!step.started_at)patch.started_at=new Date().toISOString();if(st==='Concluído'){patch.completed_at=new Date().toISOString();patch.completed_by=window.user?.id||null}else{patch.completed_at=null;patch.completed_by=null}const u=await sb().from('asset_steps').update(patch).eq('id',id);if(u.error)throw new Error(u.error.message);await syncAgenda(id,st);const ar=await sb().from('asset_steps').select('status').eq('asset_id',step.asset_id);if(!ar.error&&ar.data?.length){const done=ar.data.filter(x=>norm(x.status)==='concluido').length;await sb().from('assets').update({status:done===ar.data.length?'Concluído':done?'Em andamento':'Não iniciado',updated_at:new Date().toISOString()}).eq('id',step.asset_id)}const ag=await sb().from('agenda_items').select('commission_id').eq('asset_step_id',id).maybeSingle();if(ag.data?.commission_id)await rollupCommission(ag.data.commission_id);if(window.loadProduction)await window.loadProduction();if(window.appRefresh)await window.appRefresh()}catch(e){alert(e.message||'Não foi possível atualizar.')}finally{lock=false}}
window.bithousePhase3={changeStep,syncAgenda,rollupCommission};
})();
