/* BITHOUSE — PHASE 11: correções de inteligência + participantes */
(function(){'use strict';
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function normProgress(v){const n=Number(v||0);return n>1?n/100:n}
function fixPercentages(){document.querySelectorAll('#capacityInsights em,.forecast-row em').forEach(e=>{const n=parseFloat(e.textContent);if(Number.isFinite(n)&&n>100)e.textContent=Math.round(n/100)+'%'});document.querySelectorAll('#capacityInsights .forecast-row').forEach(r=>{const e=r.querySelector('em');if(e){const n=parseFloat(e.textContent);if(Number.isFinite(n))e.textContent=Math.min(100,Math.max(0,n))+'%'}})}
async function getMembers(id){if(!window.sb)return[];const r=await window.sb.from('commission_members').select('id,collaborator_name,role').eq('commission_id',id).order('created_at');return r.data||[]}
function participantStyle(){if($('#bh11Style'))return;const s=document.createElement('style');s.id='bh11Style';s.textContent='.bh11-box{margin-top:14px;padding-top:14px;border-top:1px solid #e7edf6}.bh11-title{font-size:10px;font-weight:900;letter-spacing:.8px;color:#8290a9;text-transform:uppercase}.bh11-list{display:flex;flex-wrap:wrap;gap:6px;margin:8px 0}.bh11-chip{padding:6px 10px;border-radius:999px;background:#f2f6fc;color:#30466f;font:800 11px Nunito}.bh11-add{width:100%;margin-top:6px}.bh11-modal{position:fixed;inset:0;background:rgba(12,25,52,.35);display:flex;align-items:center;justify-content:center;padding:20px;z-index:9999}.bh11-modal.hidden{display:none}.bh11-dialog{width:min(480px,100%);background:#fff;border-radius:22px;padding:22px;box-shadow:0 20px 60px rgba(0,0,0,.18)}.bh11-dialog h3{margin:4px 0 16px}.bh11-dialog select,.bh11-dialog input{width:100%;box-sizing:border-box;margin:5px 0;padding:11px;border:1px solid #d9e1ef;border-radius:12px}.bh11-row{display:flex;justify-content:space-between;align-items:center;padding:9px 0;border-bottom:1px solid #edf1f7}.bh11-actions{display:flex;gap:8px;margin-top:16px}.bh11-actions button{flex:1}';document.head.appendChild(s)}
function attachParticipants(){const grid=$('#commissionGrid');if(!grid)return;grid.querySelectorAll('.card[data-commission-id]').forEach(card=>{if(card.querySelector('.bh11-box'))return;const id=card.dataset.commissionId;const box=document.createElement('div');box.className='bh11-box';box.innerHTML='<div class="bh11-title">Participantes da comissão</div><div class="bh11-list"><span class="muted">Nenhum cadastrado</span></div><button type="button" class="ghost-btn small bh11-add">+ Adicionar participante</button>';card.appendChild(box);refreshParticipants(box,id);box.querySelector('button').onclick=()=>openParticipants(id,card.querySelector('h3')?.textContent||'Comissão')})}
async function refreshParticipants(box,id){const list=await getMembers(id);const host=box.querySelector('.bh11-list');if(host)host.innerHTML=list.length?list.map(m=>`<span class="bh11-chip">${esc(m.collaborator_name)}${m.role?' · '+esc(m.role):''}</span>`).join(''):'<span class="muted">Nenhum cadastrado</span>'}
function modal(){if($('#bh11Modal'))return;const m=document.createElement('div');m.id='bh11Modal';m.className='bh11-modal hidden';m.innerHTML='<div class="bh11-dialog"><div class="eyebrow">EQUIPE DA COMISSÃO</div><h3 id="bh11NameTitle">Participantes</h3><div id="bh11Rows"></div><select id="bh11Person"><option value="">Selecionar participante</option><option>scothboss</option><option>Heitor</option><option>Matheus</option></select><input id="bh11Role" placeholder="Função (opcional)"><div class="bh11-actions"><button class="ghost-btn" id="bh11Close">Fechar</button><button class="primary-btn" id="bh11Add">Adicionar</button></div></div></div>';document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m)e=>m.classList.add('hidden')});$('#bh11Close').onclick=()=>m.classList.add('hidden')}
async function openParticipants(id,title){modal();$('#bh11NameTitle').textContent=title;const rows=$('#bh11Rows'),list=await getMembers(id);rows.innerHTML=list.length?list.map(x=>`<div class="bh11-row"><span><b>${esc(x.collaborator_name)}</b>${x.role?' · '+esc(x.role):''}</span><button class="ghost-btn small" data-remove="${esc(x.id)}">Remover</button></div>`).join(''):'<div class="muted">Nenhum participante cadastrado.</div>';$('#bh11Modal').classList.remove('hidden');$('#bh11Add').onclick=async()=>{const person=$('#bh11Person').value;if(!person)return;const exists=await getMembers(id);if(exists.some(x=>x.collaborator_name.toLowerCase()===person.toLowerCase()))return alert('Esse participante já está nesta comissão.');const r=await window.sb.from('commission_members').insert({commission_id:id,collaborator_name:person,role:$('#bh11Role').value.trim()||null});if(r.error)return alert(r.error.message);$('#bh11Person').value='';$('#bh11Role').value='';await openParticipants(id,title);setTimeout(()=>{document.querySelectorAll('#commissionGrid .card[data-commission-id]').forEach(c=>{if(c.dataset.commissionId===id)refreshParticipants(c.querySelector('.bh11-box'),id)})},50)};rows.querySelectorAll('[data-remove]').forEach(b=>b.onclick=async()=>{const r=await window.sb.from('commission_members').delete().eq('id',b.dataset.remove);if(r.error)return alert(r.error.message);await openParticipants(id,title)})}
function init(){participantStyle();modal();attachParticipants();fixPercentages();const grid=$('#commissionGrid');if(grid)new MutationObserver(()=>{attachParticipants();fixPercentages()}).observe(grid,{childList:true,subtree:true});const cap=$('#capacityInsights');if(cap)new MutationObserver(fixPercentages).observe(cap,{childList:true,subtree:true,characterData:true});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,700));else setTimeout(init,700);
})();
