/* BITHOUSE — participantes externos da comissão
   Agenda exclusiva aos sócios. Colaboradores ficam apenas registrados na comissão.
*/
(function(){'use strict';
const sb=()=>window.sb,$=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const names=['scothboss','Heitor','Matheus'];let observer=null;
function style(){if($('#bh10Style'))return;const s=document.createElement('style');s.id='bh10Style';s.textContent='.bh10-members{margin-top:12px;padding-top:12px;border-top:1px solid #e7edf6}.bh10-members-title{font-size:10px;font-weight:900;letter-spacing:.7px;text-transform:uppercase;color:#8290a9;margin-bottom:7px}.bh10-chips{display:flex;gap:6px;flex-wrap:wrap}.bh10-chip{display:inline-flex;align-items:center;padding:6px 9px;border-radius:999px;background:#f2f6fc;color:#30466f;font:800 11px Nunito}.bh10-manage{margin-top:8px;width:100%}.bh10-list{display:grid;gap:8px;margin:14px 0}.bh10-row{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:10px 12px;border:1px solid #e1e8f3;border-radius:12px;background:#fff}.bh10-row span{font-weight:800;color:#243a61}.bh10-add{display:flex;gap:8px}.bh10-add select,.bh10-add input{flex:1;min-width:0;border:1px solid #d9e1ef;border-radius:12px;padding:10px;background:#fff;font:700 12px Nunito}';document.head.appendChild(s)}
async function members(id){const r=await sb().from('commission_members').select('id,collaborator_name,role').eq('commission_id',id).order('created_at');return r.data||[]}
async function renderChips(box,id){const list=await members(id),chips=box.querySelector('[data-bh10-chips]');if(!chips)return;chips.innerHTML=list.length?list.map(m=>`<span class="bh10-chip">${esc(m.collaborator_name)}${m.role?' · '+esc(m.role):''}</span>`).join(''):'<span class="muted">Nenhum cadastrado</span>'}
function attach(){const grid=$('#commissionGrid');if(!grid)return;grid.querySelectorAll('.card[data-commission-id]').forEach(card=>{if(card.querySelector('.bh10-manage'))return;const id=card.dataset.commissionId,box=document.createElement('div');box.className='bh10-members';box.innerHTML='<div class="bh10-members-title">Participantes da comissão</div><div class="bh10-chips" data-bh10-chips><span class="muted">Carregando...</span></div><button type="button" class="ghost-btn small bh10-manage">+ Adicionar participante</button>';card.appendChild(box);renderChips(box,id);box.querySelector('.bh10-manage').onclick=()=>open(id,card.querySelector('h3')?.textContent||'Comissão')})}
function modal(){if($('#bh10Modal'))return;const m=document.createElement('div');m.id='bh10Modal';m.className='bh-modal hidden';m.innerHTML='<div class="bh-dialog"><button class="bh-close" data-x>×</button><span class="eyebrow">EQUIPE DA COMISSÃO</span><h2 id="bh10Title">Participantes</h2><div class="bh10-list" id="bh10List"></div><div class="bh10-add"><select id="bh10Name"></select><input id="bh10Role" placeholder="Função (opcional)"></div><div class="bh-actions"><button class="production-action" data-x>Fechar</button><button class="bh-save" id="bh10Save">Adicionar</button></div></div>';document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m||e.target.closest('[data-x]'))m.classList.add('hidden')})}
async function open(id,title){modal();$('#bh10Title').textContent=title;$('#bh10Name').innerHTML='<option value="">Selecionar participante</option>'+names.map(n=>`<option>${esc(n)}</option>`).join('');$('#bh10Role').value='';const list=await members(id);$('#bh10List').innerHTML=list.length?list.map(m=>`<div class="bh10-row"><span>${esc(m.collaborator_name)}${m.role?' · '+esc(m.role):''}</span><button class="ghost-btn small" data-del="${esc(m.id)}">Remover</button></div>`).join(''):'<div class="muted">Nenhum participante cadastrado.</div>';$('#bh10Modal').classList.remove('hidden');$('#bh10Save').onclick=async()=>{const name=$('#bh10Name').value;if(!name)return;const existing=await members(id);if(existing.some(x=>x.collaborator_name.toLowerCase()===name.toLowerCase())){alert('Esse participante já está nesta comissão.');return}const r=await sb().from('commission_members').insert({commission_id:id,collaborator_name:name,role:$('#bh10Role').value.trim()||null});if(r.error){alert(r.error.message);return}await open(id,title)};$('#bh10List').querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{const r=await sb().from('commission_members').delete().eq('id',b.dataset.del);if(r.error){alert(r.error.message);return}await open(id,title)})}
function init(){style();modal();attach();if(observer)observer.disconnect();const grid=$('#commissionGrid');if(grid){observer=new MutationObserver(()=>attach());observer.observe(grid,{childList:true,subtree:true)}}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,500));else setTimeout(init,500);
})();
