-- BITHOUSE OPERATIONS — SUPABASE SCHEMA
-- Execute this entire file in Supabase > SQL Editor.
-- This version intentionally uses auth.users as the source of truth for profile IDs.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  role text not null default 'colaborador',
  specialty text,
  hours_per_day numeric(5,2) not null default 6,
  days_per_week integer not null default 6,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, name, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'name', split_part(coalesce(new.email,''),'@',1), 'Membro'),
    coalesce(new.raw_user_meta_data->>'role', 'colaborador')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  client text,
  status text not null default 'Planejamento',
  priority text not null default 'Média',
  progress numeric(5,4) not null default 0 check (progress >= 0 and progress <= 1),
  owner_id uuid references public.profiles(id) on delete set null,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.commissions (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  client text,
  status text not null default 'Planejamento',
  priority text not null default 'Média',
  progress numeric(5,4) not null default 0 check (progress >= 0 and progress <= 1),
  owner_id uuid references public.profiles(id) on delete set null,
  deadline date,
  start_date date,
  map_name text,
  notes text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.commission_members (
  id uuid primary key default gen_random_uuid(),
  commission_id uuid not null references public.commissions(id) on delete cascade,
  profile_id uuid references public.profiles(id) on delete set null,
  collaborator_name text,
  role text,
  created_at timestamptz not null default now(),
  unique (commission_id, profile_id)
);

create table if not exists public.assets (
  id uuid primary key default gen_random_uuid(),
  commission_id uuid not null references public.commissions(id) on delete cascade,
  name text not null,
  category text,
  map_name text,
  model_status boolean not null default false,
  model_by uuid references public.profiles(id) on delete set null,
  texture_status boolean not null default false,
  texture_by uuid references public.profiles(id) on delete set null,
  rig_status boolean not null default false,
  rig_by uuid references public.profiles(id) on delete set null,
  export_status boolean not null default false,
  export_by uuid references public.profiles(id) on delete set null,
  estimated_hours numeric(7,2) not null default 0,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tasks (
  id uuid primary key default gen_random_uuid(),
  commission_id uuid references public.commissions(id) on delete cascade,
  asset_id uuid references public.assets(id) on delete cascade,
  title text not null,
  task_type text,
  assignee_id uuid references public.profiles(id) on delete set null,
  collaborator_name text,
  status text not null default 'Pendente',
  estimated_hours numeric(7,2) not null default 0,
  due_date date,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.agenda_items (
  id uuid primary key default gen_random_uuid(),
  commission_id uuid references public.commissions(id) on delete cascade,
  task_id uuid references public.tasks(id) on delete cascade,
  profile_id uuid references public.profiles(id) on delete set null,
  collaborator_name text,
  date date not null,
  task text not null,
  hours numeric(7,2) not null default 0,
  status text not null default 'Pendente',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.activity_log (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id) on delete set null,
  action text not null,
  entity_type text,
  entity_id uuid,
  details jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

insert into public.settings(key,value)
values ('operations', '{"reserve":0.20}')
on conflict (key) do nothing;

-- Updated-at helper
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

do $$
declare t text;
begin
  foreach t in array array[
    'profiles','projects','commissions','commission_members','assets',
    'tasks','agenda_items','activity_log','settings'
  ]
  loop
    execute format('drop trigger if exists trg_updated_at_%I on public.%I', t, t);
    if t in ('profiles','projects','commissions','assets','tasks','agenda_items','settings') then
      execute format(
        'create trigger trg_updated_at_%I before update on public.%I for each row execute procedure public.set_updated_at()',
        t,t
      );
    end if;
  end loop;
end $$;

-- RLS: only authenticated Bithouse users can access operational data.
alter table public.profiles enable row level security;
alter table public.projects enable row level security;
alter table public.commissions enable row level security;
alter table public.commission_members enable row level security;
alter table public.assets enable row level security;
alter table public.tasks enable row level security;
alter table public.agenda_items enable row level security;
alter table public.activity_log enable row level security;
alter table public.settings enable row level security;

drop policy if exists "authenticated profiles" on public.profiles;
create policy "authenticated profiles" on public.profiles
for all to authenticated using (true) with check (true);

drop policy if exists "authenticated projects" on public.projects;
create policy "authenticated projects" on public.projects
for all to authenticated using (true) with check (true);

drop policy if exists "authenticated commissions" on public.commissions;
create policy "authenticated commissions" on public.commissions
for all to authenticated using (true) with check (true);

drop policy if exists "authenticated commission_members" on public.commission_members;
create policy "authenticated commission_members" on public.commission_members
for all to authenticated using (true) with check (true);

drop policy if exists "authenticated assets" on public.assets;
create policy "authenticated assets" on public.assets
for all to authenticated using (true) with check (true);

drop policy if exists "authenticated tasks" on public.tasks;
create policy "authenticated tasks" on public.tasks
for all to authenticated using (true) with check (true);

drop policy if exists "authenticated agenda_items" on public.agenda_items;
create policy "authenticated agenda_items" on public.agenda_items
for all to authenticated using (true) with check (true);

drop policy if exists "authenticated activity_log" on public.activity_log;
create policy "authenticated activity_log" on public.activity_log
for all to authenticated using (true) with check (true);

drop policy if exists "authenticated settings" on public.settings;
create policy "authenticated settings" on public.settings
for all to authenticated using (true) with check (true);

-- Enable Realtime for the operational tables.
do $$
begin
  begin alter publication supabase_realtime add table public.commissions; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.assets; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.tasks; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.agenda_items; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.profiles; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.commission_members; exception when duplicate_object then null; end;
end $$;

-- Bithouse core users.
-- IMPORTANT: replace the emails below with the exact emails already created in Authentication > Users.
-- These inserts are intentionally NOT included because IDs must come from auth.users.
